server:
  port: 9011

spring:
  application:
    name: cloud-alibaba-nacos-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        register-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

