server:
  port: 8083

spring:
  application:
    name: Cloud-Alibaba-Consumer-83
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        register-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  nacos-user-service: http://cloud-alibaba-nacos-payment
